### ISSUE TITLE
Following upgrade to 0.4, can't see the remaining level of the filter

### ISSUE THREAD

**Issue by XilviuX** [Tvalley71/dantherm#48]
This could be a consequence of a botched upgrade + an updated translation file, however after the upgrade to 0.4, the template sensor indicating the 'age' of the filter is not available anymore. As a consequence it's also not visible anymore in the graphical view.

![Capture](https://github.com/Tvalley71/dantherm/assets/163339991/ef597888-32ba-43d0-8335-8bb07f53d8fd)

![Capture2](https://github.com/Tvalley71/dantherm/assets/163339991/f31fc985-b2bc-49be-8606-eecd9f30d60e)

**Comment by Tvalley71** [comment]
Are you using another prefix than "Dantherm" when adding the integration? This prefix is now part of the unique ids, not only the friendly names. This means the helper you have created to covert the "level" attribute on filter remain to a sensor, may need to be changed.
If this is not the case I have some other things I need you to check.

**Comment by Tvalley71** [comment]
The _dantherm_ bit will be whatever prefix you use (with _ instead of spaces):
```
{{ state_attr('sensor.dantherm_filter_remain', 'level') }}
```

**Comment by XilviuX** [comment]
Sorry for the delay in replying and thank you for the help.

I used the Dantherm prefix by default, and I didn't see the filter remain value (I think). Then I renamed the device to dantherm (all lower case) and chose to rename the entities too. No change.

Currently if I filter the Entity list by "sensor.dantherm", I do see the Filter Remain Level

<img width="1172" alt="Capture d’écran 2024-07-08 à 01 20 41" src="https://github.com/Tvalley71/dantherm/assets/163339991/995d4a75-8389-4dc1-a633-dbfaae4a310e">

but it's value is unknown:
<img width="1168" alt="Capture d’écran 2024-07-08 à 01 22 15" src="https://github.com/Tvalley71/dantherm/assets/163339991/ec5a390a-78f1-49d5-bdd1-64250315a13f">

Any idea?

**Comment by XilviuX** [comment]
> This means the helper you have created to covert the "level" attribute on filter remain to a sensor, may need to be changed. 

Why do you say 'the helper you have created'? I thought it was created by the integration?

**Comment by Tvalley71** [comment]
Because creating that sensor is part of the detailed description of how to make the Dantherm app look-alike picture-elements card in the integration description. 

The level is an attribute on the filter_remain sensor. If click on the filter_remain sensor you should see the level at the bottom. Sorry for the danish pictures, I hope you get the sense of it.

![image](https://github.com/Tvalley71/dantherm/assets/83084467/0227bc38-5ae5-4d2b-bd76-83022b98059c)

The picture-elements card cannot access an attribute directly, therefore the need to create the helper to convert the attribute to a sensor.

What I need you to check is, if the helper still points to the filter_remain sensor to grab the level attribute. If the unique id names has changed since you created the helper, this would be the reason for the helper not being available anymore.

Click on the filter remain level helper and click the cog icon.

![image](https://github.com/Tvalley71/dantherm/assets/83084467/d0e08dfe-e2f6-4a6d-a234-71d25a937618)

If the template is not correct anymore, you need to change it.

Let me know if this is the reason.

Tvalley71

**Comment by XilviuX** [comment]
This is of course the reason :) I completely forgot that I had created this template... Thanks for the reminder.

And indeed the 'issue' was that I had changed something in the translation for this value, and I didn't take the change into account.

Thanks again, this is fixed now.

**Comment by Tvalley71** [comment]
Nice to hear.
